dist: trusty
language: rust
rust: nightly

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=thumbv7m-none-eabi

before_install:
  - sudo apt-get update

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

branches:
  only:
    - auto
    - master

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
