dist: trusty
language: rust
rust: nightly

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=thumbv7m-none-eabi

before_install:
  - sudo apt-get update

install:
  - bash ci/install.sh

script:
  - cargo build --target $TARGET

branches:
  only: master

notifications:
  email:
    on_success: never
