language: rust
rust: nightly

matrix:
  # clear matrix
  exclude:
    - rust: nightly
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=thumbv7m-none-eabi
      dist: trusty
      sudo: required

before_install:
  - sudo apt-get update

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

branches:
  only:
    - auto
    - master

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
